-- =====================================================================
--  Raccoon Lab v2 - Esquema Firebird 5
--  Lo aplica la app Go al arrancar (solo si la tabla USUARIOS no existe)
--  Cada sentencia termina en ;  (sin triggers ni SET TERM)
-- =====================================================================

-- ---------- Catálogo de roles ----------
CREATE TABLE ROLES (
    CLAVE        VARCHAR(10)  NOT NULL PRIMARY KEY,
    DESCRIPCION  VARCHAR(40)  NOT NULL
);

INSERT INTO ROLES (CLAVE, DESCRIPCION) VALUES ('ADMIN', 'Administrador');
INSERT INTO ROLES (CLAVE, DESCRIPCION) VALUES ('PROFESOR', 'Maestro');
INSERT INTO ROLES (CLAVE, DESCRIPCION) VALUES ('ALUMNO', 'Alumno');

-- ---------- Grupos (IRD-71, IRD-72, ...) ----------
CREATE TABLE GRUPOS (
    CODIGO   VARCHAR(15)  NOT NULL PRIMARY KEY,
    CREADO   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ---------- Usuarios (alumnos, maestros y admins) ----------
-- MATRICULA = matrícula del alumno o clave del maestro/admin (es el login)
-- TIPO      = archivo con el que se importó: alumnos | maestros | admins
-- GRUPO     = solo alumnos; NULL para maestros y admins
CREATE TABLE USUARIOS (
    MATRICULA      VARCHAR(20)   NOT NULL PRIMARY KEY,
    NOMBRE         VARCHAR(120)  NOT NULL,
    PASSWORD_HASH  VARCHAR(100)  NOT NULL,
    TIPO           VARCHAR(10)   NOT NULL,
    GRUPO          VARCHAR(15),
    ACTIVO         BOOLEAN       DEFAULT TRUE NOT NULL,
    CREADO         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACTUALIZADO    TIMESTAMP,
    ULTIMO_ACCESO  TIMESTAMP,
    CONSTRAINT CHK_USUARIOS_TIPO CHECK (TIPO IN ('alumnos', 'maestros', 'admins')),
    CONSTRAINT FK_USUARIOS_GRUPO FOREIGN KEY (GRUPO)
        REFERENCES GRUPOS (CODIGO) ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------- Roles de cada usuario (independientes) ----------
CREATE TABLE USUARIO_ROLES (
    MATRICULA  VARCHAR(20)  NOT NULL,
    ROL        VARCHAR(10)  NOT NULL,
    CONSTRAINT PK_USUARIO_ROLES PRIMARY KEY (MATRICULA, ROL),
    CONSTRAINT FK_UR_USUARIO FOREIGN KEY (MATRICULA)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROL FOREIGN KEY (ROL) REFERENCES ROLES (CLAVE)
);

-- ---------- Maestros asignados a cada grupo (varios por grupo) ----------
CREATE TABLE GRUPO_DOCENTES (
    CODIGO     VARCHAR(15)  NOT NULL,
    MATRICULA  VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_GRUPO_DOCENTES PRIMARY KEY (CODIGO, MATRICULA),
    CONSTRAINT FK_GD_GRUPO FOREIGN KEY (CODIGO)
        REFERENCES GRUPOS (CODIGO) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_GD_USUARIO FOREIGN KEY (MATRICULA)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------- Laboratorios GNS3 activos ----------
CREATE TABLE WORKSPACES (
    ID            VARCHAR(40)  NOT NULL PRIMARY KEY,
    DUENO         VARCHAR(20)  NOT NULL,
    PUERTO_BASE   INTEGER      NOT NULL,
    TOKEN         VARCHAR(16)  NOT NULL,
    CODIGO_COLAB  VARCHAR(15),
    INICIO        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_WS_PUERTO UNIQUE (PUERTO_BASE),
    CONSTRAINT UQ_WS_DUENO UNIQUE (DUENO),
    CONSTRAINT UQ_WS_CODIGO UNIQUE (CODIGO_COLAB),
    CONSTRAINT FK_WS_DUENO FOREIGN KEY (DUENO)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------- Invitados en laboratorios de equipo ----------
-- UNIQUE(MATRICULA): un usuario solo puede estar en un laboratorio a la vez
CREATE TABLE WORKSPACE_MIEMBROS (
    ID_WORKSPACE  VARCHAR(40)  NOT NULL,
    MATRICULA     VARCHAR(20)  NOT NULL,
    UNIDO         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_WS_MIEMBROS PRIMARY KEY (ID_WORKSPACE, MATRICULA),
    CONSTRAINT UQ_WS_MIEMBRO UNIQUE (MATRICULA),
    CONSTRAINT FK_WSM_WS FOREIGN KEY (ID_WORKSPACE)
        REFERENCES WORKSPACES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_WSM_USUARIO FOREIGN KEY (MATRICULA)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------- Invitaciones entre compañeros ----------
CREATE TABLE INVITACIONES (
    ID            VARCHAR(16)  NOT NULL PRIMARY KEY,
    ID_WORKSPACE  VARCHAR(40)  NOT NULL,
    EMISOR        VARCHAR(20)  NOT NULL,
    RECEPTOR      VARCHAR(20)  NOT NULL,
    ESTADO        VARCHAR(12)  DEFAULT 'PENDIENTE' NOT NULL,
    CREADA        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_INV_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'EXPIRADA')),
    CONSTRAINT FK_INV_WS FOREIGN KEY (ID_WORKSPACE)
        REFERENCES WORKSPACES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_INV_EMISOR FOREIGN KEY (EMISOR)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_INV_RECEPTOR FOREIGN KEY (RECEPTOR)
        REFERENCES USUARIOS (MATRICULA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IDX_INV_RECEPTOR_ESTADO ON INVITACIONES (RECEPTOR, ESTADO);
